<?php
if (!defined('ABSPATH')) exit;
final class OAEODI_AI_PDF {
  public static function boot(): void {
    add_action('admin_post_oaeodi_ai_process',[__CLASS__,'handle']);
    add_action('admin_menu',[__CLASS__,'menu'],99);
  }
  public static function menu(): void { add_submenu_page('oae-document-intelligence','AI PDF Engine','AI PDF Engine','manage_options','oaeodi-ai-pdf',[__CLASS__,'screen']); }
  public static function screen(): void {
    if(!current_user_can('manage_options')) return; global $wpdb;
    $docs=$wpdb->get_results("SELECT id,title,source_filename,status,extraction_method,quality_score,source_path FROM {$wpdb->prefix}oaeodi_docs ORDER BY id DESC");
    echo '<div class="wrap"><h1>OAE Document Intelligence v2.3.1 – AI PDF Engine</h1>';
    echo '<p>ใช้ Gemini native PDF understanding เมื่อ GDCC ไม่มี Poppler/Tesseract. เอกสารจะยังไม่เข้า KB จนกว่าจะ Verify & Publish จากหน้าหลัก.</p>';
    echo '<p><b>Gemini:</b> '.(self::ready()?'ready':'API key not found in OAE AI Assistance').'</p><table class="widefat striped"><thead><tr><th>ID</th><th>เอกสาร</th><th>Status</th><th>Method</th><th>Quality</th><th></th></tr></thead><tbody>';
    foreach($docs as $d){echo '<tr><td>'.(int)$d->id.'</td><td>'.esc_html($d->title).'<br><small>'.esc_html($d->source_filename).'</small></td><td>'.esc_html($d->status).'</td><td>'.esc_html($d->extraction_method).'</td><td>'.esc_html($d->quality_score).'</td><td>';
      if($d->source_path && is_readable($d->source_path)){echo '<form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="oaeodi_ai_process"><input type="hidden" name="doc_id" value="'.(int)$d->id.'">';wp_nonce_field('oaeodi_ai_process_'.(int)$d->id);submit_button('AI Process PDF','secondary','submit',false);echo '</form>';}else echo 'Upload original PDF first'; echo '</td></tr>';}
    echo '</tbody></table></div>';
  }
  public static function ready(): bool { return self::key()!==''; }
  public static function handle(): void {
    if(!current_user_can('manage_options')) wp_die('Permission denied'); $id=absint($_POST['doc_id']??0); check_admin_referer('oaeodi_ai_process_'.$id); global $wpdb; $t=$wpdb->prefix.'oaeodi_docs';
    $d=$wpdb->get_row($wpdb->prepare("SELECT * FROM $t WHERE id=%d",$id)); if(!$d||!$d->source_path||!is_readable($d->source_path)) self::go('Source PDF not found',$id); if(!self::ready()) self::go('Gemini API key not found in OAE AI Assistance',$id);
    $wpdb->update($t,['status'=>'ai_processing','extraction_method'=>'gemini_pdf','updated_at'=>current_time('mysql')],['id'=>$id]); self::audit($id,'ai_start',['model'=>self::model()]);
    try{$r=self::run($d->source_path,$d->title);$text=self::normalize($r['full_text']??'');if(mb_strlen($text)<80)throw new RuntimeException('AI returned too little text');$q=self::quality($text);$v=(int)($r['verification_score']??0);$flags=array_values(array_unique(array_merge($q['flags'],$r['flags']??[],['external_ai_processed','human_verification_required'])));$status=$v>=90?'ai_verified':'needs_review';$m=$r['metadata']??[];$m['ai_provider']='gemini';$m['ai_model']=self::model();$m['verification_score']=$v;$m['ai_usage']=$r['usage']??[];
      $wpdb->update($t,['title'=>sanitize_text_field($m['title']??$d->title),'doc_type'=>sanitize_key($m['document_type']??$d->doc_type??'general'),'agency'=>sanitize_text_field($m['agency']??''),'document_no'=>sanitize_text_field($m['document_no']??''),'document_date'=>sanitize_text_field($m['document_date']??''),'effective_date'=>sanitize_text_field($m['effective_date']??''),'page_count'=>absint($r['page_count']??0),'extraction_method'=>'gemini_pdf_double_verify','status'=>$status,'coverage'=>'full_document_ai_extract','quality_score'=>max(0,min(100,round(($q['score']+$v)/2,2))),'quality_flags'=>implode(',',$flags),'raw_text'=>$text,'normalized_text'=>$text,'metadata_json'=>wp_json_encode($m,JSON_UNESCAPED_UNICODE),'relationships_json'=>wp_json_encode($r['relationships']??[],JSON_UNESCAPED_UNICODE),'updated_at'=>current_time('mysql')],['id'=>$id]); self::pages($id,$text); self::audit($id,'ai_complete',['verification_score'=>$v,'status'=>$status,'flags'=>$flags]); self::go('AI PDF processing completed. Review then Verify & Publish to KB.',$id);
    }catch(Throwable $e){$wpdb->update($t,['status'=>'needs_review','quality_flags'=>'ai_processing_failed,human_verification_required','updated_at'=>current_time('mysql')],['id'=>$id]);self::audit($id,'ai_error',['message'=>$e->getMessage()]);self::go('AI Process failed: '.$e->getMessage(),$id);}
  }
  private static function key(): string { return trim((string)apply_filters('oaeodi_gemini_api_key',(string)get_option('oaeaiu_gemini_api_key',(string)get_option('oaeodi_gemini_api_key','')))); }
  private static function model(): string { $m=trim((string)get_option('oaeodi_gemini_model','gemini-2.5-flash'));return $m?:'gemini-2.5-flash'; }
  private static function run(string $path,string $title): array {$f=self::upload($path);$name=$f['name']??'';$uri=$f['uri']??'';if(!$name||!$uri)throw new RuntimeException('Gemini upload did not return file URI');try{self::wait($name);$a=self::generate($uri,self::extract_prompt($title));$b=self::generate($uri,self::verify_prompt());$x=self::json($a['text']);$y=self::json($b['text']);if(!$x||!$y)throw new RuntimeException('AI JSON parse failed');$flags=[];if(($a['finish']??'')==='MAX_TOKENS')$flags[]='ai_output_truncated';$score=self::compare($x,$y,$flags);$doc=$x['document']??[];$full=(string)($x['full_text']??'');foreach(($x['tables']??[]) as $tb){if(is_array($tb))$full.="\n\n### ".($tb['title']??'Table')."\n".($tb['markdown']??'');}return ['full_text'=>$full,'page_count'=>absint($doc['page_count']??$y['page_count']??0),'metadata'=>['title'=>$doc['title']??$title,'document_type'=>$doc['document_type']??'general','agency'=>$doc['agency']??'','document_no'=>$doc['document_no']??'','document_date'=>$doc['document_date']??'','effective_date'=>$doc['effective_date']??'','critical_facts'=>$x['critical_facts']??[],'warnings'=>$x['warnings']??[]],'relationships'=>$x['relationships']??[],'verification_score'=>$score,'flags'=>$flags,'usage'=>['extract'=>$a['usage']??[],'verify'=>$b['usage']??[]]];}finally{self::delete($name);}}
  private static function upload(string $path): array {$size=filesize($path);if(!$size||$size>50*1024*1024)throw new RuntimeException('PDF empty or exceeds 50 MB');$s=wp_remote_post('https://generativelanguage.googleapis.com/upload/v1beta/files?key='.rawurlencode(self::key()),['timeout'=>60,'headers'=>['Content-Type'=>'application/json','X-Goog-Upload-Protocol'=>'resumable','X-Goog-Upload-Command'=>'start','X-Goog-Upload-Header-Content-Length'=>(string)$size,'X-Goog-Upload-Header-Content-Type'=>'application/pdf'],'body'=>wp_json_encode(['file'=>['display_name'=>basename($path)]])]);if(is_wp_error($s))throw new RuntimeException($s->get_error_message());$u=wp_remote_retrieve_header($s,'x-goog-upload-url');if(!$u)throw new RuntimeException('No Gemini upload URL');$bytes=file_get_contents($path);$r=wp_remote_request($u,['method'=>'POST','timeout'=>180,'headers'=>['Content-Type'=>'application/pdf','Content-Length'=>(string)$size,'X-Goog-Upload-Offset'=>'0','X-Goog-Upload-Command'=>'upload, finalize'],'body'=>$bytes]);unset($bytes);if(is_wp_error($r))throw new RuntimeException($r->get_error_message());$j=json_decode(wp_remote_retrieve_body($r),true);return is_array($j['file']??null)?$j['file']:(is_array($j)?$j:[]);}
  private static function wait(string $name): void {for($i=0;$i<30;$i++){$r=wp_remote_get('https://generativelanguage.googleapis.com/v1beta/'.ltrim($name,'/').'?key='.rawurlencode(self::key()),['timeout'=>30]);if(is_wp_error($r))throw new RuntimeException($r->get_error_message());$j=json_decode(wp_remote_retrieve_body($r),true);$s=strtoupper((string)($j['state']??''));if($s==='ACTIVE')return;if($s==='FAILED')throw new RuntimeException('Gemini file processing failed');sleep(2);}throw new RuntimeException('Gemini file processing timeout');}
  private static function generate(string $uri,string $prompt): array {$ep='https://generativelanguage.googleapis.com/v1beta/models/'.rawurlencode(self::model()).':generateContent?key='.rawurlencode(self::key());$payload=['contents'=>[['role'=>'user','parts'=>[['fileData'=>['mimeType'=>'application/pdf','fileUri'=>$uri]],['text'=>$prompt]]]],'generationConfig'=>['temperature'=>0,'responseMimeType'=>'application/json','maxOutputTokens'=>32768]];$r=wp_remote_post($ep,['timeout'=>180,'headers'=>['Content-Type'=>'application/json'],'body'=>wp_json_encode($payload,JSON_UNESCAPED_UNICODE)]);if(is_wp_error($r))throw new RuntimeException($r->get_error_message());$j=json_decode(wp_remote_retrieve_body($r),true);if(wp_remote_retrieve_response_code($r)>=300)throw new RuntimeException((string)($j['error']['message']??'Gemini HTTP error'));$txt='';foreach(($j['candidates'][0]['content']['parts']??[]) as $p)if(isset($p['text']))$txt.=$p['text'];return ['text'=>$txt,'finish'=>$j['candidates'][0]['finishReason']??'','usage'=>$j['usageMetadata']??[]];}
  private static function json(string $s): array {$s=trim($s);$s=preg_replace('/^```(?:json)?\s*/i','',$s)??$s;$s=preg_replace('/\s*```$/','',$s)??$s;$j=json_decode($s,true);return is_array($j)?$j:[];}
  private static function compare(array $a,array $b,array &$flags): int {$score=100;$d=$a['document']??[];foreach(['document_no','document_date','page_count'] as $k){$x=self::canon((string)($d[$k]??''));$y=self::canon((string)($b[$k]??''));if($x&&$y&&$x!==$y){$score-=15;$flags[]='ai_verification_mismatch_'.$k;}}if(!empty($b['red_flags'])){$score-=10;$flags[]='ai_verifier_red_flags';}return max(0,$score);}
  private static function canon(string $s): string {$s=mb_strtolower(trim($s));$s=preg_replace('/\s+/u','',$s)??$s;return preg_replace('/[^ก-๙a-z0-9\.\/\-]+/u','',$s)??$s;}
  private static function extract_prompt(string $t): string {return 'อ่าน PDF เอกสารราชการไทยทุกหน้าอย่างเคร่งครัด ห้ามเดา ตรวจเลขหนังสือ วันที่ เลขข้อ ตัวเลข หน่วยเงิน ชื่อหน่วยงาน และตาราง ส่ง JSON เท่านั้น {"document":{"title":"","document_type":"regulation|order|circular|guideline|form|other","agency":"","document_no":"","document_date":"","effective_date":"","page_count":0},"full_text":"ใส่ [[PAGE:1]] ตามหน้า","tables":[{"title":"","page":1,"markdown":""}],"relationships":[{"type":"amends|replaces|repeals|references|related","target":"","evidence":""}],"critical_facts":[{"label":"","value":"","page":1,"evidence":""}],"warnings":[]}. ถ้าอ่านไม่ชัดให้ใช้ [อ่านไม่ชัด] ห้ามคาดเดา. ชื่อเดิม: '.$t;}
  private static function verify_prompt(): string {return 'ตรวจ PDF รอบที่ 2 โดยอิสระ ห้ามอาศัยผลรอบแรกและห้ามเดา ส่ง JSON เท่านั้น {"title":"","document_no":"","document_date":"","page_count":0,"critical_facts":[{"label":"","value":"","page":1}],"red_flags":[]} เน้นอัตราเงิน จำนวนวัน ผู้มีอำนาจ ข้อกำหนด ระยะเวลา เลขข้อและเงื่อนไข.';}
  private static function normalize(string $s): string {$s=wp_check_invalid_utf8($s,true);if(class_exists('Normalizer')){$n=Normalizer::normalize($s,Normalizer::FORM_C);if($n!==false)$s=$n;}$s=preg_replace('/[ \t]+/u',' ',$s)??$s;$s=preg_replace('/\r\n?/u',"\n",$s)??$s;return trim($s);}
  private static function quality(string $s): array {$n=max(1,mb_strlen($s));$sc=100;$f=[];$bad=substr_count($s,'�');if($bad){$sc-=min(35,($bad/$n)*1000);$f[]='replacement_chars';}if($n<300){$sc-=30;$f[]='low_text_volume';}return ['score'=>max(0,min(100,round($sc,2))),'flags'=>$f];}
  private static function pages(int $id,string $s): void {global $wpdb;$t=$wpdb->prefix.'oaeodi_pages';$wpdb->delete($t,['doc_id'=>$id]);$p=preg_split('/\[\[PAGE:(\d+)\]\]/u',$s,-1,PREG_SPLIT_DELIM_CAPTURE);$pages=[];if($p&&count($p)>2){for($i=1;$i<count($p)-1;$i+=2)$pages[(int)$p[$i]]=trim($p[$i+1]);}else$pages[1]=$s;foreach($pages as $n=>$x)$wpdb->insert($t,['doc_id'=>$id,'page_no'=>$n,'normalized_text'=>$x,'quality_score'=>self::quality($x)['score'],'quality_flags'=>'ai_pdf','created_at'=>current_time('mysql'),'updated_at'=>current_time('mysql')]);}
  private static function delete(string $name): void {if($name)wp_remote_request('https://generativelanguage.googleapis.com/v1beta/'.ltrim($name,'/').'?key='.rawurlencode(self::key()),['method'=>'DELETE','timeout'=>30]);}
  private static function audit(int $id,string $action,array $detail=[]): void {global $wpdb;$wpdb->insert($wpdb->prefix.'oaeodi_audit',['doc_id'=>$id,'user_id'=>get_current_user_id()?:null,'action'=>$action,'detail_json'=>wp_json_encode($detail,JSON_UNESCAPED_UNICODE),'created_at'=>current_time('mysql')]);}
  private static function go(string $m,int $id): void {$u=admin_url('admin.php?page=oae-document-intelligence&doc_id='.$id);wp_safe_redirect(add_query_arg('oaeodi_msg',rawurlencode($m),$u));exit;}
}
